---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Cognito Setup
Resources:
  CognitoUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: !Ref UserPoolName
  CognitoUserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName: !Ref UserPoolClientName
      UserPoolId: !Ref CognitoUserPool
Outputs:
  UserPoolId:
    Description: 'Cognito User Pool ID'
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Description: 'Cognito User Pool Client ID'
    Value: !Ref CognitoUserPoolClient
Parameters:
  UserPoolName:
    Type: String
    Description: 'Name of the Cognito User Pool'
  UserPoolClientName:
    Type: String
    Description: 'Name of the Cognito User Pool Client'
