AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TokensTable
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  TableName:
    Value: !Ref TokensTable
    Export:
      Name: DynamoDBTableName
