---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS DynamoDB Setup
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'TokensTable'
      AttributeDefinitions:
        - AttributeName: 'UserId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'UserId'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  TableName:
    Description: 'DynamoDB Table Name'
    Value: !Ref DynamoDBTable
