---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS S3 Setup
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
Outputs:
  BucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref S3Bucket
Parameters:
  S3BucketName:
    Type: String
    Description: 'Name of the S3 bucket'
