AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: your-frontend-bucket-name
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Export:
      Name: S3BucketName
